[[process]]
name = "Install"
type = "setup"
command = "yarn install"

[[process]]
name = "Dev Server"
type = "daemon"
command = "vite dev"
url = "http://localhost:5173"

[[process]]
name = "Build"
type = "task"
command = "npm run build"

[[process]]
name = "Typecheck"
type = "check"
command = "npm run typecheck"

[[process]]
name = "Test"
type = "check"
command = "npm run test"
